<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\TourPackage;
use App\Models\Location;

class TourPackageSeeder extends Seeder
{
    public function run(): void
    {
        $locationIds = Location::whereIn('city', [
            'Huamanga',
            'Cangallo',
            'Vilcashuamán',
            'Quinua',
            'Huanta',
            'Sucre',
            'Parinacochas',
            'Paucar del Sara Sara',
        ])->pluck('id', 'city')->toArray();

        $packages = [
            [
                'category_id'     => 2,
                'location_id'     => $locationIds['Cangallo'] ?? 2,
                'title'           => 'Aguas Turquesas de Millpu',
                'description'     => 'Descubre las impresionantes lagunas de color turquesa en Cangallo. Un paraíso natural único en el Perú con más de 15 lagunas escalonadas rodeadas de vegetación andina.',
                'price'           => 125.00,
                'duration_days'   => 1,
                'includes_guide'  => true,
                'includes_food'   => true,
                'includes_hotel'  => false,
                'image_url'       => '/images/packages/millpu.webp',
                'available_slots' => 15,
                'status'          => true,
            ],
            [
                'category_id'     => 1,
                'location_id'     => $locationIds['Vilcashuamán'] ?? 3,
                'title'           => 'Vilcashuamán Imperial',
                'description'     => 'Visita el centro ceremonial inca de Vilcashuamán, considerado el ombligo del Tahuantinsuyo. Incluye visita al ushnu, templo del sol y la luna, y el estanque ceremonial.',
                'price'           => 100.00,
                'duration_days'   => 2,
                'includes_guide'  => true,
                'includes_food'   => true,
                'includes_hotel'  => true,
                'image_url'       => '/images/packages/vilcashuaman.webp',
                'available_slots' => 15,
                'status'          => true,
            ],
            [
                'category_id'     => 1,
                'location_id'     => $locationIds['Quinua'] ?? 4,
                'title'           => 'Pampa de Ayacucho y Quinua',
                'description'     => 'Recorre el campo de batalla donde se libró la última batalla por la independencia de América. Visita el obelisco conmemorativo y el picturesque pueblo artesanal de Quinua.',
                'price'           => 120.00,
                'duration_days'   => 1,
                'includes_guide'  => true,
                'includes_food'   => false,
                'includes_hotel'  => false,
                'image_url'       => '/images/packages/pampa de ayacucho.webp',
                'available_slots' => 15,
                'status'          => true,
            ],
            [
                'category_id'     => 4,
                'location_id'     => $locationIds['Huamanga'] ?? 1,
                'title'           => 'Templos Coloniales de Huamanga',
                'description'     => 'Recorre las 33 iglesias coloniales de la Ciudad de las Iglesias. Visita la Catedral, San Francisco de Asís, La Merced y la Iglesia de Santo Domingo con guía especializado.',
                'price'           => 90.00,
                'duration_days'   => 1,
                'includes_guide'  => true,
                'includes_food'   => false,
                'includes_hotel'  => false,
                'image_url'       => '/images/packages/templos_ayacucho.webp',
                'available_slots' => 15,
                'status'          => true,
            ],
            [
                'category_id'     => 2,
                'location_id'     => $locationIds['Huanta'] ?? 5,
                'title'           => 'Huanta y sus Lagunas',
                'description'     => 'Explora la ciudad de la eterna primavera. Visita las lagunas de Ñahuinpuquio y el bosque de puyas de Raimondi. Ideal para amantes de la naturaleza y fotografía.',
                'price'           => 150.00,
                'duration_days'   => 2,
                'includes_guide'  => true,
                'includes_food'   => true,
                'includes_hotel'  => true,
                'image_url'       => '/images/packages/huanta_lagunas.webp',
                'available_slots' => 12,
                'status'          => true,
            ],
            [
                'category_id'     => 1,
                'location_id'     => $locationIds['Huamanga'] ?? 1,
                'title'           => 'Zona Arqueológica Wari',
                'description'     => 'Descubre la capital del Imperio Wari, la primera civilización urbana de los Andes. Recorre las ruinas de la antigua ciudad con guía arqueólogo especializado.',
                'price'           => 80.00,
                'duration_days'   => 1,
                'includes_guide'  => true,
                'includes_food'   => false,
                'includes_hotel'  => false,
                'image_url'       => '/images/packages/wari.webp',
                'available_slots' => 10,
                'status'          => true,
            ],
            [
                'category_id'     => 3,
                'location_id'     => $locationIds['Sucre'] ?? 6,
                'title'           => 'Sabores y tradiciones de Sucre',
                'description'     => 'Degusta la cocina local y conoce tradiciones vivas en Sucre. Una experiencia cultural con mercados y patrimonio religioso.',
                'price'           => 50.00,
                'duration_days'   => 1,
                'includes_guide'  => true,
                'includes_food'   => true,
                'includes_hotel'  => false,
                'image_url'       => '/images/packages/sucre.webp',
                'available_slots' => 13,
                'status'          => true,
            ],
            [
                'category_id'     => 2,
                'location_id'     => $locationIds['Parinacochas'] ?? 7,
                'title'           => 'Laguna Parinacochas y Flamencos',
                'description'     => 'Explora la laguna y las montañas del sur de Ayacucho. Ideal para caminatas y fotografía en un paisaje de altura. Observa flamencosrosados en su hábitat natural.',
                'price'           => 170.00,
                'duration_days'   => 2,
                'includes_guide'  => true,
                'includes_food'   => true,
                'includes_hotel'  => true,
                'image_url'       => '/images/packages/parinacochas.webp',
                'available_slots' => 14,
                'status'          => true,
            ],
            [
                'category_id'     => 4,
                'location_id'     => $locationIds['Paucar del Sara Sara'] ?? 8,
                'title'           => 'Ruta de Miradores en Paucar del Sara Sara',
                'description'     => 'Recorre los principales miradores del distrito y conoce los pueblos serranos con paisajes espectaculares.',
                'price'           => 140.00,
                'duration_days'   => 2,
                'includes_guide'  => true,
                'includes_food'   => false,
                'includes_hotel'  => true,
                'image_url'       => '/images/packages/paucar_de_sarasara.webp',
                'available_slots' => 16,
                'status'          => true,
            ],
            [
                'category_id'     => 5,
                'location_id'     => $locationIds['Cangallo'] ?? 2,
                'title'           => 'Ecoturismo en Cangallo',
                'description'     => 'Immérgete en la naturaleza de Cangallo con senderos ecológicos, observación de aves y contacto directo con comunidades locales que protegen su entorno.',
                'price'           => 180.00,
                'duration_days'   => 2,
                'includes_guide'  => true,
                'includes_food'   => true,
                'includes_hotel'  => false,
                'image_url'       => '/images/packages/ecoturismo_cangallo.webp',
                'available_slots' => 15,
                'status'          => true,
            ],
            [
                'category_id'     => 2,
                'location_id'     => $locationIds['Lucanas'] ?? 2,
                'title'           => 'Cascadas de Lucanas',
                'description'     => 'Camina hacia las impresionantes cascadas de Lucanas, escondidas entre quebradas andinas. Una experiencia de aventura perfecta para los amantes del senderismo.',
                'price'           => 180.00,
                'duration_days'   => 1,
                'includes_guide'  => true,
                'includes_food'   => false,
                'includes_hotel'  => false,
                'image_url'       => '/images/packages/cascadas_lucanas.webp',
                'available_slots' => 12,
                'status'          => true,
            ],
            [
                'category_id'     => 4,
                'location_id'     => $locationIds['Huamanga'] ?? 1,
                'title'           => 'Semana Santa en Ayacucho',
                'description'     => 'Vive la celebración más importante de Ayacucho con procesiones, alfombras florales y tradiciones religiosas centenarias. Una experiencia cultural única.',
                'price'           => 150.00,
                'duration_days'   => 3,
                'includes_guide'  => true,
                'includes_food'   => true,
                'includes_hotel'  => true,
                'image_url'       => '/images/packages/semana_santa.webp',
                'available_slots' => 20,
                'status'          => true,
            ],
            [
                'category_id'     => 1,
                'location_id'     => $locationIds['Vilcashuamán'] ?? 3,
                'title'           => 'Complejo Arqueológico Intihuatana',
                'description'     => 'Explora el misterioso complejo arqueológico Intihuatana, un centro ceremonial Inca con vista panoramic a los Andes. Descubre sus secretos astrónomicos.',
                'price'           => 200.00,
                'duration_days'   => 2,
                'includes_guide'  => true,
                'includes_food'   => true,
                'includes_hotel'  => true,
                'image_url'       => '/images/packages/intiwatana.webp',
                'available_slots' => 12,
                'status'          => true,
            ],
            [
                'category_id'     => 5,
                'location_id'     => $locationIds['Huanta'] ?? 5,
                'title'           => 'Bosque de Puyas Raimondi',
                'description'     => 'Camina entre las enormes puyas de Raimondi, las plantas más grandes del mundo. Un ecosistema único donde podrás observar colibries gigantes y flora endémica.',
                'price'           => 190.00,
                'duration_days'   => 2,
                'includes_guide'  => true,
                'includes_food'   => true,
                'includes_hotel'  => false,
                'image_url'       => '/images/packages/puyas_raimondi.webp',
                'available_slots' => 10,
                'status'          => true,
            ],
            [
                'category_id'     => 2,
                'location_id'     => $locationIds['Parinacochas'] ?? 7,
                'title'           => 'Trekking Altoandino Parinacochas',
                'description'     => 'Desafía los senderos de altura en los Andes de Parinacochas. Trekking extremo con vistas a lagunas cristalinas, nevados y fauna silvestre de altura.',
                'price'           => 280.00,
                'duration_days'   => 3,
                'includes_guide'  => true,
                'includes_food'   => true,
                'includes_hotel'  => true,
                'image_url'       => '/images/packages/trekking_parinacochas.webp',
                'available_slots' => 8,
                'status'          => true,
            ],
        ];

        foreach ($packages as $package) {
            TourPackage::updateOrCreate(['title' => $package['title']], $package);
        }
    }
}
