import {
    MapPin,
    Calendar,
    Users,
    Home,
    Compass,
    Search,
    FileText,
    Phone,
    Star,
    Check,
    X,
    AlertTriangle,
    Target,
    CreditCard,
    Clock,
    HelpCircle,
    UtensilsCrossed,
    Sparkles,
    Shield,
    TrendingUp,
    TrendingDown,
    AlertCircle,
    Eye,
    EyeOff,
    Plus,
    Minus,
    ChevronDown,
    ChevronUp,
    Menu,
    X as XIcon,
    ArrowLeft,
    ArrowRight,
    Mail,
    MessageCircle,
    Loader2,
    CheckCircle2,
    XCircle,
    Info,
    Globe,
    Briefcase,
    Plane,
    Hotel,
    Camera,
    Building,
    Wallet,
    QrCode,
    Trophy,
    Banknote,
    Mountain,
    Waves,
    Sun,
    Droplet,
    Landmark,
    Pencil,
    Trash2,
    Package,
    Grid,
    Coffee,
    Truck,
    BarChart3,
    Tag,
    ExternalLink,
    Edit2,
    LayoutDashboard,
    User,
    LogOut,
    Map,
    SlidersHorizontal,
    Filter,
    ArrowUpDown,
    CheckSquare,
    Square,
    Send,
    Heart,
    Share2,
    Eye as EyeIcon,
    MapPinned,
    Settings,
    Brain,
    Headphones,
    Lightbulb,
} from 'lucide-react';

const iconMap = {
    'map-pin': MapPin,
    'calendar': Calendar,
    'users': Users,
    'home': Home,
    'compass': Compass,
    'search': Search,
    'file-text': FileText,
    'phone': Phone,
    'star': Star,
    'check': Check,
    'x': X,
    'alert-triangle': AlertTriangle,
    'target': Target,
    'credit-card': CreditCard,
    'clock': Clock,
    'help-circle': HelpCircle,
    'utensils': UtensilsCrossed,
    'sparkles': Sparkles,
    'shield': Shield,
    'eye': Eye,
    'eye-off': EyeOff,
    'plus': Plus,
    'minus': Minus,
    'chevron-down': ChevronDown,
    'chevron-up': ChevronUp,
    'menu': Menu,
    'x-icon': XIcon,
    'arrow-left': ArrowLeft,
    'arrow-right': ArrowRight,
    'mail': Mail,
    'message-circle': MessageCircle,
    'loader': Loader2,
    'check-circle': CheckCircle2,
    'x-circle': XCircle,
    'alert-circle': AlertCircle,
    'info': Info,
    'globe': Globe,
    'briefcase': Briefcase,
    'plane': Plane,
    'hotel': Hotel,
    'camera': Camera,
    'building': Building,
    'wallet': Wallet,
    'qr-code': QrCode,
    'trophy': Trophy,
    'banknote': Banknote,
    'mountain': Mountain,
    'waves': Waves,
    'sunrise': Sun,
    'wheat': Droplet,
    'landmark': Landmark,
    'pencil': Pencil,
    'trash2': Trash2,
    'trending-up': TrendingUp,
    'trending-down': TrendingDown,
    'package': Package,
    'grid': Grid,
    'coffee': Coffee,
    'truck': Truck,
    'bar-chart': BarChart3,
    'tag': Tag,
    'external-link': ExternalLink,
    'edit-2': Edit2,
    'layout-dashboard': LayoutDashboard,
    'user': User,
    'log-out': LogOut,
    'map': Map,
    'sliders-horizontal': SlidersHorizontal,
    'filter': Filter,
    'arrow-up-down': ArrowUpDown,
    'check-square': CheckSquare,
    'square': Square,
    'send': Send,
    'heart': Heart,
    'share-2': Share2,
    'eye': EyeIcon,
    'map-pinned': MapPinned,
    'settings': Settings,
    'brain': Brain,
    'headphones': Headphones,
    'lightbulb': Lightbulb,
};

export default function Icon({ name, size = 16, className = '', ...props }) {
    const IconComponent = iconMap[name];

    if (!IconComponent) {
        console.warn(`Icon "${name}" not found`);
        return null;
    }

    return (
        <IconComponent
            size={size}
            className={className}
            {...props}
        />
    );
}
